# Site settings
title: Hanz Christian Andrade Mendez
description: Simple web resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hanz Christian Andrade Mendez
user_description: I am an IT professional experienced in the mystic arts of modern technology. With over 4 years worth of battle experience. Highly motivated and extremely shy in the language of love.
user_title: Software Engineer
email: hnzmndz@gmail.com
# twitter_username: lorem_ipsum
instagram_username: hnzmndz
facebook_username: hahahanz
linkedin_username: hnzmndz
github_username:  hanzindahaus
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
